name: deploy-to-cloud-run

on:
  push:
    branches:
      - dev

jobs:
  build_to_gcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: cat .env into root
        run: echo "VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}" > .env

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.WIF_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'
      - name: Configure Docker for GCR
        run: gcloud auth configure-docker gcr.io --quiet

      - name: Build Docker image
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/black-at-api:${{ github.sha }} .

      - name: Push Docker image to GCR
        env:
          GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/black-at-api:${{ github.sha }}

  deploy_to_cloud_run:
    runs-on: ubuntu-latest
    needs: build_to_gcr
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Authenticate to Google Cloud
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.WIF_SERVICE_ACCOUNT_KEY }}'

      - name: Set up Cloud SDK
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy blackat-user-frontend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/black-at-api:${{ github.sha }} \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --min-instances 1 \
            --set-env-vars VITE_SERVER_URL=${{ secrets.VITE_SERVER_URL }}
            